---
# Source: gloo-ee/templates/23-extauth-upstream.yaml
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  labels:
    app: gloo
    gloo: extauth
  name: extauth
  namespace: gloo-system
spec:
  useHttp2: true
  healthChecks:
  - timeout: 5s
    interval: 10s
    unhealthyThreshold: 3
    healthyThreshold: 3
    grpcHealthCheck:
      serviceName: ext-auth
  kube:
    serviceName: extauth
    serviceNamespace: gloo-system
    servicePort:  8083
    serviceSpec:
      grpc: {}
