---
# Source: gloo-ee/templates/30-license-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: gloo
    gloo: license
  name: license
  namespace: gloo-system
type: Opaque
data:
  license-key: 'ZXlKbGVIQWlPakUyTVRZM01EY3hNakFzSW1saGRDSTZNVFl4TkRBeU9EY3lNQ3dpYXlJNklsTkdkRWhhUVNJc0lteDBJam9pZEhKcFlXd2lmUS43dk1ETGNYcnBNaF9tWHVhLVFuUHVUY3hlSDU3QWJjRnl4TnV3ZnZ6cTJZ'
