---
# Source: gloo-ee/templates/32-apiserver-service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: gloo
    gloo: apiserver-ui
  name: apiserver-ui
  namespace: gloo-system
