---
# Source: gloo-ee/templates/61-rolebinding-settings-user.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: glooe-settings-user-role-binding-gloo-system
  labels:
    app: gloo
    gloo: rbac
subjects:
  - kind: ServiceAccount
    name: observability
    namespace: gloo-system
roleRef:
  kind: ClusterRole
  name: settings-user-gloo-system
  apiGroup: rbac.authorization.k8s.io
