---
# Source: gloo-ee/templates/62-rate-limit-service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: gloo
    gloo: rate-limit
  name: rate-limit
  namespace: gloo-system
