---
# Source: gloo-ee/templates/8-observability-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: observability-upstream-role-gloo-system
  labels:
    app: gloo
    gloo: observability
rules:
  - apiGroups: ["gloo.solo.io"]
    resources: ["upstreams"]
    verbs: ["get", "list", "watch"]
---
# Source: gloo-ee/templates/8-observability-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: observability-upstream-rolebinding-gloo-system
  labels:
    app: gloo
    gloo: observability
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: observability-upstream-role-gloo-system
subjects:
  - kind: ServiceAccount
    name: observability
    namespace: gloo-system
