---
# Source: gloo-ee/templates/8-observability-service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: gloo
    gloo: observability
  name: observability
  namespace: gloo-system
