---
# Source: gloo-ee/templates/9-observability-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gloo
    gloo: observability
  name: observability
  namespace: gloo-system
spec:
  selector:
    matchLabels:
      app: gloo
      gloo: observability
  template:
    metadata:
      labels:
        app: gloo
        gloo: observability
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9091"
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: observability
      volumes:
        - name: upstream-dashboard-template
          configMap:
            name: gloo-observability-config
            items:
            - key: DASHBOARD_JSON_TEMPLATE
              path: dashboard-template.json
      containers:
        - image: quay.io/solo-io/observability-ee:1.8.23
          imagePullPolicy: IfNotPresent
          name: observability
          volumeMounts:
            - name: upstream-dashboard-template
              mountPath: /observability
              readOnly: true
          env:
            - name: GLOO_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: license
                  key: license-key
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: START_STATS_SERVER
              value: "true"
          envFrom:
            - configMapRef:
                name: gloo-observability-config
            - secretRef:
                name: gloo-observability-secrets
      securityContext:
        runAsNonRoot: true
        runAsUser: 10101
