---
# Source: gloo-ee/templates/9-observability-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: gloo
    gloo: gloo-observability-secrets
  name: gloo-observability-secrets
  namespace: gloo-system
type: Opaque
data:
  # default to the built-in grafana username/password, but allow it to be overridden through the customGrafana object
  GRAFANA_USERNAME: "YWRtaW4="
  GRAFANA_PASSWORD: "YWRtaW4="
