# https://www.ory.sh/docs/kratos/reference/configuration
version: v0.9.0-alpha.2
kratos:
  config:
    dsn: postgres://dev:password@kratos-pg.kratos:5432/kratosdb
    secrets:
      default:
        - dolore occaecat nostrud Ut
        - sit et commodoaute ut voluptate consectetur Duis
    courier:
      smtp:
        connection_uri: smtps://foo:bar@my-mailserver:1234/?skip_ssl_verify=true
    serve:
      public:
        base_url: http://0.0.0.0:4433/
        cors:
          enabled: true
      admin:
        base_url: http://0.0.0.0:4434/
    selfservice:
      default_browser_return_url: http://0.0.0.0:4455
      methods:
        password:
          enabled: true
      flows:
        error:
          ui_url: http://0.0.0.0:4455/error
        settings:
          ui_url: http://0.0.0.0:4455/settings
          privileged_session_max_age: 15m
        recovery:
          enabled: true
          ui_url: http://0.0.0.0:4455/recovery
        verification:
          enabled: true
          ui_url: http://0.0.0.0:4455/verification
          after:
            default_browser_return_url: http://0.0.0.0:4455
        logout:
          after:
            default_browser_return_url: http://0.0.0.0:4455/login
        login:
          ui_url: http://0.0.0.0:4455/login
          lifespan: 10m
        registration:
          lifespan: 10m
          ui_url: http://0.0.0.0:4455/registration
          after:
            password:
              hooks:
                - hook: session
    identity:
      default_schema_id: ''
      schemas:
        - id: employee
          url: file:///schema/identity.schema.json

deployment:
  extraVolumes:
    - name: kratos-configmap-volume
      configMap:
        name: kratos-configmap
  extraVolumeMounts:
    - name: kratos-configmap-volume
      mountPath: /schema
      readOnly: true
