kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: sso

resources:
  - deployment.yaml
  - http-service.yaml
  - namespace.yaml

configMapGenerator:
  - name: selfservice-ui-env
    envs:
      - config/selfservice-ui.env
